config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  root :to => "pages#home"
    
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  
  match '/contact' => 'pages#contact'
  match '/about'   => 'pages#about'
  match '/help'    => 'pages#help'
  match '/signup'  => 'users#new'
  match '/signin'  => 'sessions#new'
  match '/signout' => 'sessions#destroy'
  
  match '/users/:id/microposts' => 'microposts#index'
  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved:
    </h2>
    <p>There were problems with the following fields:</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <ul class='microposts' summary="User microposts">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </ul>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li>
  <div class='gravatar'>
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </div>
  <div class='micropost'>
    <div class='user'>
      <%= link_to feed_item.user.name, feed_item.user %>
    </div>
    <div class='content'>
      <%= wrap(feed_item.content) %>
    </div>

    <div class='timestamp'>
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </div>
  </div>
  <% if current_user?(feed_item.user) %>
    <div class='delete'>
      <%= link_to "delete", feed_item, :method => :delete,
                                       :confirm => "You sure?",
                                       :title => feed_item.content %>
    </div>                                   
  <% end %>
  
  
</li>

app/views/shared/_home_not_signed_in.html.erb
<h1>Sample App</h1>
<p>
  This is the home page for the <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/shared/_home_signed_in.html.erb
<table class='front' summary="For signed-in users">
  <tr>
    <td class='main'>
      <h1 class='micropost'>What's up?</h1>
      <%= render 'shared/micropost_form' %>
      <%= render 'shared/feed' %>
    </td>
    <td class='sidebar round'>
      <%= render 'shared/user_info' %>
      <%= render 'shared/stats' %>
    </td>
  </tr>
</table>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => f.object%>
  <div class='field'>
    <%= f.text_area :content, :onkeyup => "javascript: UpdateCounter();" %>
  </div>
  <div class='countdown'>
    (<label id='countdown_value'>140</label>)
  </div>
  <div class='actions'>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% #on a profile page, @user will be set, but on Home page, need to use current_user %>
<% @user ||= current_user %>

<div class='stats'>
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id='following' class='stat'>
            <%= @user.following.count %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id='followers' class='stat'>
            <%= @user.followers.count %> followers
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_user_info.html.erb
<div class='user_info'>
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class='user_name'>
      <%= current_user.name %>
    </span>
    <span class='microposts'>
      <%= pluralize(current_user.microposts.count, "micropost") %>
    </span>
  </a>
</div>